# Default config for Kelson's Bukkit Plugin
motd: ^5Hello player %s!
motdConsole: ^fHello console!
# Welcome message coming soon!
welcomemsg:
- &6Welcome to kelsoncraft %s!
PlayerMove: false
BlockBreak: false
NightVisionTime: 9999
PickupBlockedItemMessage: Hello
debugMode: true
KBPUsage: |
 Hello %s, use /kbp help to find out info about this command!