name: KBP-mini
#Old name Kelsons-Plugin
main: me.Kelson.Main
version: 1.0.4_10
description: This is the custom plugin for the kelsoncraft server!
author: kelson8
#load: Startup
api-version: 1.16

commands:
  kelson-help:
    description: This is the help for my plugin 
    permission: kelson.help
    permission-message: You do not have permission to use this command!

  fly:
    description: This is the fly command usage /fly [player].
    permission: kelson.fly
    permission-message: You do not have permission to use this command!

  showxp:
    description: Shows the amount of xp the player has.

  location:
    description: Shows the location of the world your in.

  ipbans:
    description: Shows the ips that are banned in the server.
    permission: kelson.ipbans
    permission-message: You do not have permission to use this command!

  kelson-reload: 
    description: This reloads the config.yml
    permission: kelson.reload
    permission-message: You do not have permission to use this command!
  
  serverinfo:
   description: Shows the server info to the player
   permission: kelson.serverinfo
   permission-message: You do not have permission to use this command!

  playerinfo:
   description: Shows a players info

  nohunger:
    description: This command turns your hunger off
    
  lightning:
    description: Strikes lightning at the player.
    aliases: [smite] # [smite, lightning, ....]

  nightvision:
    description: Enables/disables nightvision
    aliases: [nv]
    
  lightningstick:
    description: Gives player a lightning rod
    aliases: [ls, lightningrod]
 

permissions:
   kelson.*:
     description: Gives all permissions using Kelsons Plugin.
     default: op
     children:
       kelson.fly: true
       kelson.fly.others: true
       kelson.ipbans: true
       kelson.reload: true
       kelson.nofire: true
       kelson.nametag: true
       kelson.help: true
       kelson.serverinfo: true
       kelson.location.others: true
       kelson.nohunger: true
       kelson.smite: true
       kelson.smite.others: true
       kelson.destory: true
       kelson.playerinfo.others: true
       kelson.nightvision: true
       kelson.nightvision.others: true
       kelson.lightning_rod: true
       kelson.lightning_rod.self: true
       kelson.place.bedrock: true
       
   kelson.default.*:
     description: Gives the default permissions using Kelsons Plugin.
     default: true
     children:
       kelson.location: true
       kelson.playerinfo: true
     