name: KBP
#Old name Kelsons-Plugin
main: net.Kelsoncraft.KBP.KbpMain
version: 1.0.5
description: This is the custom plugin for the kelsoncraft server!
author: kelson8
softdepend:
  - Vault
  - Multiverse-Core
  - PlotSquared
#softdepend: [TagAPI, SQLibrary]
#load: Startup
api-version: 1.20

commands:
  fly:
    description: This is the fly command usage /fly [player].
    permission: kbp.fly
    permission-message: You do not have permission to use this command!

  location:
    description: Shows the location of the world your in.

  ipbans:
    description: Shows the ips that are banned in the server.
    permission: kbp.ipbans
    permission-message: You do not have permission to use this command!

  kheal:
    description: Heals the player heals another player if a name is specified.
    permission: kbp.heal
    permission-message: You do not have permission to use this command!

  kmotd:
    description: Shows the motd to the players from my plugin
    permission: kbp.kmotd
    permission-message: You do not have permission to use this command!

  setkmotd:
    description: Sets the message for /kmotd
    permisson: kbp.setkmotd
    permission-message: You do not have permission to use this command!

  kelson-reload: 
    description: This reloads the config.yml
    permission: kbp.reload
    permission-message: You do not have permission to use this command!
   
  test:
   description: Test
   permission: kbp.test
   permission-message: You do not have permission to use that command!
  
  serverinfo:
   description: Shows the server info to the player
   permission: kbp.serverinfo
   permission-message: You do not have permission to use this command!

  playerinfo:
   description: Shows a players info

  # This one isn't implemented yet.
  nohunger:
    description: This command turns your hunger off
    
  lightning:
    description: Strikes lightning at the player.
    aliases: [smite] # [smite, lightning, ....]

  god:
    description: Gives the player god mode.

  nightvision:
    description: Enables/disables nightvision
    aliases: [nv]

  test1:
    description: Testing
    
  lightningstick:
    description: Gives player a lightning rod
    aliases: [ls, lightningrod]

  # This one isn't implemented yet.
  itemrename:
    description: Renames item in hand, color codes with with symbol &
    aliases: [ir]
    
  flyspeed:
    description: Changes your flying speed
    aliases: [fs]

  # This one isn't implemented yet.
  inv_test:
    description: Testing creating an inventory.
    
  kbp:
    description: Reload command and version command.
    
  enderchest:
    description: Opens an ender chest for you.
    aliases: [ec]

  # This one isn't completed yet.
  ranklist:
    description: Shows a list of the ranks on the server.

  configtest1:
    description: Add player uuid to config.

  configtest2:
    description: List player names from config.

  bossbar:
    description: Displays a bossbar.
    permission: kbp.bossbar
    #usage: "/Usage: <command> [on|off]"

  menu:
    description: Opens a test menu

  kbal:
    description: Shows your balance

  givemoney:
    description: Give you some money.

  keco:
    description: Add, remove, and reset your money.

  flower:
    description: Gives you a flower with special properties.

  getworld:
    description: Shows your current world.

  createworld:
    description: Create a new world, not setup yet.

permissions:
   kbp.*:
     description: Gives all permissions using KBP.
     default: op
     children:
       kbp.fly: true
       kbp.fly.others: true
       kbp.enablewhitelist: true
       kbp.ipbans: true
       kbp.reload: true
       kbp.heal: true
       kbp.nametag: true
       kbp.kmotd: true
       kbp.help: true
       kbp.configtest: true
       kbp.test: true
       kbp.serverinfo: true
       kbp.location.others: true
       kbp.nohunger: true
       kbp.smite: true
       kbp.smite.others: true
       kbp.destory: true
       kbp.playerinfo.others: true
       kbp.god: true
       kbp.god.others: true
       kbp.nightvision: true
       kbp.nightvision.others: true
       kbp.testcommands: true
       kbp.lightning_rod: true
       kbp.lightning_rod.self: true
       kbp.flyspeed: true
       kbp.place.bedrock: true
       kbp.inv_test: true
       kbp.enderchest.others: true
       kbp.enderchest: true
       # New test
       kbp.bossbar: true
       kbp.menu.cooldown: true
       kbp.givemoney: true
       kbp.eco: true

   kbp.default.*:
     description: Gives the default permissions using KBP.
     default: true
     children:
       kbp.location: true
       kbp.kmotd: true
       kbp.playerinfo: true
       kbp.kbal: true
     